name: Larastan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  larastan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.3' # Adjust the PHP version as needed

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --no-interaction

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse --memory-limit=1G # Adjust memory limit as needed
